// Package caddy renders the reverse proxy configuration shared by every app on
// a host.
//
// One Caddy instance owns ports 80 and 443 and every app runs on a loopback
// port, so adding an app is a configuration change rather than a firewall
// change. The file is regenerated from the app specs rather than edited by hand,
// which is what keeps the proxy from drifting away from what is declared.
package caddy

import (
	"fmt"
	"sort"
	"strings"
)

// Site is one domain served by the proxy.
type Site struct {
	// Domain is the canonical hostname.
	Domain string
	// Aliases are additional hostnames redirected to Domain.
	Aliases []string
	// Port is the loopback port the app listens on.
	Port int
}

// Render builds the whole Caddyfile.
//
// Sites are sorted so the output only changes when something actually changed:
// comparing the rendered result against what is on the host is how a reload is
// avoided when nothing moved.
func Render(email string, sites []Site) string {
	sorted := make([]Site, len(sites))
	copy(sorted, sites)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Domain < sorted[j].Domain })

	var b strings.Builder
	b.WriteString("# Generated by dodeploy from the app specs on this host.\n")
	b.WriteString("# Do not edit by hand: the next deploy overwrites it.\n\n")

	b.WriteString("{\n")
	if email != "" {
		fmt.Fprintf(&b, "\temail %s\n", email)
	}
	b.WriteString("}\n\n")

	for _, s := range sorted {
		for _, alias := range s.Aliases {
			if alias == "" || alias == s.Domain {
				continue
			}
			fmt.Fprintf(&b, "%s {\n\tredir https://%s{uri} permanent\n}\n\n", alias, s.Domain)
		}

		fmt.Fprintf(&b, "%s {\n", s.Domain)
		b.WriteString("\tencode zstd gzip\n\n")
		b.WriteString("\t# The app records the real client rather than the proxy.\n")
		fmt.Fprintf(&b, "\treverse_proxy 127.0.0.1:%d {\n", s.Port)
		b.WriteString("\t\theader_up X-Real-IP {remote_host}\n")
		b.WriteString("\t}\n\n")
		b.WriteString("\theader {\n")
		b.WriteString("\t\tStrict-Transport-Security \"max-age=31536000; includeSubDomains\"\n")
		b.WriteString("\t\tX-Content-Type-Options \"nosniff\"\n")
		b.WriteString("\t\tReferrer-Policy \"strict-origin-when-cross-origin\"\n")
		b.WriteString("\t\t-Server\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// WithWWW adds a www alias for a domain unless it is already covered.
//
// The proxy redirects www to the apex, so www needs a DNS record of its own.
// Without it a registrar's parking record keeps answering for www, which looks
// like the site is half-broken.
func WithWWW(domain string, aliases []string) []string {
	if strings.HasPrefix(domain, "www.") {
		return aliases
	}
	www := "www." + domain
	for _, a := range aliases {
		if a == www {
			return aliases
		}
	}
	return append(append([]string{}, aliases...), www)
}
